apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ghcr.io/abhishek-chauhan-dev/node-app:c1412ea390b2fbdedbb1dccf9e4a9fcf90d85300
        ports:
        - containerPort: 8080
        
