apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: ghcr.io/abhishek-chauhan-dev/node-app:9c013ae448363192f47cf01b93b6985753dc9ffd
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret
        
